# Client - Your Laptop
local_host = "127.0.0.1"
local_port = 5432
remote_host = "YOUR_CLOUD_IP"
remote_port = 8443
target_host = "127.0.0.1"
target_port = 5432
cipher = "aegis128l"
psk = "CHANGE-ME"
default_token = "CHANGE-ME"
service_id = 1
num_tunnels = 2
