# Server Config - Public Server (RPI/VPS)
port = 8443
host = "0.0.0.0"
cipher = "aegis128l"
psk = "CHANGE-ME"
default_token = "CHANGE-ME"

[server.services.emby]
id = 1
mode = "reverse"
local_port = 8096    # Public port
target_host = "127.0.0.1"
target_port = 8096   # Emby port on client
